### ISSUE TITLE
Newly acquired morphs not visible in Survival morph menu

### ISSUE THREAD

**Issue by SeaborneFright** [asanetargoss/metamorph#37] opened 2020-11-13 18:47 UTC
Hello!
I am using: 
-Changeling 1.2.23 for 1.12.2
-DominionLib 2.1
-Forge 1.12.2-14.23.5.2847

Basically, despite acquiring morphs (they show up as acquired in the entity selector, i get the little "Acquired!" pop up, ect), they stop showing up in the survival morph menu after I've acquired a little number of them (around 18), rendering them effectively unusable without shifting to creative mode every time.

It is very possible that this is caused by me being stupid and I apologize in advance-
Thank and have a nice day!

**Comment by James103** [comment] 2020-11-13 18:56
Is there a scroll bar that appears in the morph selection menu? If so, can you try scrolling down to see if more morphs appear?

**Comment by asanetargoss** [comment] 2020-11-14 02:14
Thanks for submitting this bug report. There are no stupid questions. Changeling 1.2.3 was just released and is a big update incorporating a lot of upstream changes, including a new survival morph menu.

> they stop showing up in the survival morph menu

Do you mean that all the morphs have vanished? If so, one possibility is that the "User Morphs" menu was toggled. Clicking it toggles the list of morphs between opening and closing, which could make the morphs not visible. Another possibility is that there's some sort of error when trying to render a modded morph... that might show up in the logs.

**Comment by SeaborneFright** [comment] 2020-11-14 11:43
Hi, thanks for answering so quickly!
So I tried things out on my own. To clarify, the previously acquired morphs still showed up, just not the new ones (vanilla and modded alike). There was no scroll bar. I also found that the issue is sometimes fixed by closing and reopening the game, though the issue seems to repeat after some time, or on new worlds, so it's not game-ending, it's just sort of annoying.
I'm not really good with anything regarding modding or even coding, so sorry if I can't be any more precise.

**Comment by asanetargoss** [comment] 2020-11-14 15:56
Ah, in that case it sounds like the bug is that the scroll bar is not showing when it is supposed to.

**Comment by Speecker** [comment] 2020-11-27 22:03
Hey ;) I stumbled upon the same issue and did some specific testing wich got me the following result: It seems like changing your morph triggers the said issue that newly collected morphs wont be registered and shown in the selector GUI. To view them a World Reload (Going to Main Menu and reload said Save) is all it takes and as long as you do not demorph or change current moprh - any new will be registered as it should. Id say its a minor bug but i think its apreciatable if that inconvinence may be cleared out of the way.
For now bypass is to reload your Save/World to view new morphs if collected after a morph change.

**Comment by asanetargoss** [comment] 2021-01-18 00:18
Hello, please try downloading the latest version of Changeling and DominionLib and see if they fix your issue.

**Comment by asanetargoss** [comment] 2021-02-12 04:37
@Speecker Do you think you can explain how you are able to reproduce this bug with the minimum mods required to reproduce it?

I have not been able to reproduce the bug as described with the information given so far.

**Comment by Speecker** [comment] 2021-02-12 08:13
> @Speecker Do you think you can explain how you are able to reproduce this bug with the minimum mods required to reproduce it?
> 
> I have not been able to reproduce the bug as described with the information given so far.

Did some more testing and it seems like it is definitely fixed for Vanilla Mobs, but Modded Mobs dont work always.
For AOA3 (Advent of Ascension 3 / Nevermine) Mobs it seems to never work when you change your morph after loading the save-file. Tried it as well with backup-save-files and checked versions of the mods.
Cant say if it is especially AOA3 that is not working properly or other mods Mobs as well. Might have to test more to see a clear image wheather or not wich mobs won’t work correctly.

See Full ModList here: https://pastebin.com/FtaUYCzD

let me know if you need anything else like specific config.cfg or else

**Comment by asanetargoss** [comment] 2021-02-12 16:33
@Speecker What might be helpful is if you start Minecraft, reproduce the bug, then send me your most recent logs. This may help narrow down the bug more.

**Comment by Speecker** [comment] 2021-02-13 09:48
Caught it on Cam 🗡️ 

Bug Proof: https://streamable.com/swp2je

Workaround Proof: https://streamable.com/obpal2

It happened after changing Morph in Overworld, then going to the nether and slaying yet unacquired mobs and picking their morph up.
Im not sure but changning dimensions might be the trigger

**Comment by asanetargoss** [comment] 2021-02-13 16:36
>It happened after changing Morph in Overworld, then going to the nether and slaying yet unacquired mobs and picking their morph up.
> Im not sure but changning dimensions might be the trigger

This is helpful, will see if I can reproduce this.

**Comment by asanetargoss** [comment] 2021-02-28 06:05
I can indeed reproduce a morph GUI desync on 1.2.5.changeling.1. It seems to be triggered by either dying or switching dimensions... however only in survival. keepMorphs also needs to be false to reproduce, at least for the death case. Anyways, should be fixed in the new release.

**Closed as completed by asanetargoss** 2021-02-28 06:05 UTC
Labels: bug, done
