### ISSUE TITLE
"Dragon mounts 2" dragons not respecting breed

### ISSUE THREAD

**Issue by arceusplayer11** [asanetargoss/metamorph#15] opened 2020-03-30 03:12 UTC
https://www.curseforge.com/minecraft/mc-mods/dm2

Morphing into a dragon from the dragon mounts 2 mod doesn't respect it's breed. Say, I want to become an Aether breed dragon. the nbt tag for this is {Breed:aether}. It doesn't matter whether I kill an aether breed dragon, or use the creative menu to adjust the tags, or use the morph command in a command block; the breed will always be the default breed (which in this case, is the ender breed, {Breed:end}).

**Comment by asanetargoss** [comment] 2020-03-30 05:22
The fix for this would likely require adding special code to Changeling specifically to handle Dragon Mounts 2. Feature support for third-party mobs is ouside the scope of Changeling.

With that said, if you encounter a crash caused by an interaction between Changeling and Dragon Mounts 2, or you notice an exception in the logs that's related to Changeling, please do send them my way.

Check your logs after morphing and see if you find anything that looks like an error, and link it here if you do. If not then I'll close this case.

**Closed as completed** 2020-04-01 02:27 UTC
Labels: bug, wontfix, interaction
